name = "Collatz"
version = "0.1.0"
keywords = ["math", "collatz", "number-theory"]
defaultTargets = ["Collatz"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.14.0"

[[lean_lib]]
name = "Collatz"
