name = "Collatz"
version = "0.1.0"
keywords = ["math", "collatz", "number-theory"]
defaultTargets = ["Collatz"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "v4.27.0-rc1"

[[lean_lib]]
name = "Collatz"
